openapi: 3.0.0
info:
  title: RESTful API
  description: API for managing Usuarios, Pontos, and Departamentos
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /usuarios:
    get:
      summary: Get all Usuarios
      responses:
        '200':
          description: A list of Usuarios
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Usuario'
    post:
      summary: Create a new Usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsuarioCreate'
      responses:
        '201':
          description: Usuario created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'

  /usuarios/{id}:
    get:
      summary: Get a Usuario by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A single Usuario
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
        '404':
          description: Usuario not found
    put:
      summary: Update a Usuario
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsuarioUpdate'
      responses:
        '200':
          description: Usuario updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
        '404':
          description: Usuario not found
    delete:
      summary: Delete a Usuario
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Usuario deleted
        '404':
          description: Usuario not found

  /pontos:
    get:
      summary: Get all Pontos
      responses:
        '200':
          description: A list of Pontos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ponto'
    post:
      summary: Create a new Ponto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PontoCreate'
      responses:
        '201':
          description: Ponto created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ponto'

  /pontos/{id}:
    get:
      summary: Get a Ponto by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A single Ponto
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ponto'
        '404':
          description: Ponto not found
    put:
      summary: Update a Ponto
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PontoUpdate'
      responses:
        '200':
          description: Ponto updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ponto'
        '404':
          description: Ponto not found
    delete:
      summary: Delete a Ponto
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Ponto deleted
        '404':
          description: Ponto not found

  /departamentos:
    get:
      summary: Get all Departamentos
      responses:
        '200':
          description: A list of Departamentos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Departamento'
    post:
      summary: Create a new Departamento
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DepartamentoCreate'
      responses:
        '201':
          description: Departamento created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Departamento'

  /departamentos/{id}:
    get:
      summary: Get a Departamento by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A single Departamento
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Departamento'
        '404':
          description: Departamento not found
    put:
      summary: Update a Departamento
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DepartamentoUpdate'
      responses:
        '200':
          description: Departamento updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Departamento'
        '404':
          description: Departamento not found
    delete:
      summary: Delete a Departamento
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Departamento deleted
        '404':
          description: Departamento not found

components:
  schemas:
    Usuario:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
    UsuarioCreate:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
    UsuarioUpdate:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
    Ponto:
      type: object
      properties:
        id:
          type: string
        description:
          type: string
    PontoCreate:
      type: object
      properties:
        description:
          type: string
    PontoUpdate:
      type: object
      properties:
        description:
          type: string
    Departamento:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
    DepartamentoCreate:
      type: object
      properties:
        name:
          type: string
    DepartamentoUpdate:
      type: object
      properties:
        name:
          type: string